
CREATE DATABASE IF NOT EXISTS keycloak;


GRANT ALL PRIVILEGES ON keycloak.* TO 'root'@'%';


CREATE DATABASE IF NOT EXISTS sonar;
GRANT ALL PRIVILEGES ON sonar.* TO 'root'@'%';


FLUSH PRIVILEGES;

SHOW DATABASES;